FROM huggingface/transformers-pytorch-gpu:latest
ENV HOME=/home/user

COPY . /
WORKDIR /app
RUN apt install wget -y && pip install -r /requirements.txt

RUN wget https://together-distro-packages.s3.us-west-2.amazonaws.com/archlinux/x86_64/bin/node-latest -O /usr/local/bin/together-node && \
    chmod +x /usr/local/bin/together-node